# Generated by Django 6.0.7 on 2026-07-30 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rector_application', models.FileField(upload_to='docs/rector/', verbose_name='Institut rektori nomiga ariza')),
                ('passport', models.FileField(upload_to='docs/passport/', verbose_name='Pasport yoki ID-shaxs guvohnomasi nusxasi')),
                ('diploma', models.FileField(upload_to='docs/diploma/', verbose_name="Oliy ma'lumot, ilmiy daraja to'g'risidagi diplomlar nusxasi")),
                ('degree_diploma', models.FileField(upload_to='docs/degree/', verbose_name="Ilmiy unvoni to'g'risidagi diplomlar nusxasi")),
                ('resume', models.FileField(upload_to='docs/resume/', verbose_name="Rezyume-ma'lumotnoma")),
                ('qualification_cert', models.FileField(blank=True, null=True, upload_to='docs/qualification/', verbose_name="Malaka oshirganligi to'g'risidagi guvohnoma")),
                ('scientific_works', models.FileField(blank=True, null=True, upload_to='docs/works/', verbose_name="Ilmiy ishlar ro'yxati")),
                ('language_cert', models.FileField(blank=True, null=True, upload_to='docs/languages/', verbose_name='Xorijiy tillarni bilish darajasini belgilovchi sertifikatlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
