# Generated by Django 6.0.7 on 2026-08-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rejection_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Rad etish sababi'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Ariza holati'),
        ),
        migrations.AlterField(
            model_name='application',
            name='degree_diploma',
            field=models.FileField(blank=True, null=True, upload_to='docs/degree/', verbose_name="Ilmiy unvoni to'g'risidagi diplomlar nusxasi"),
        ),
        migrations.AlterField(
            model_name='application',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='docs/diploma/', verbose_name="Oliy ma'lumot, ilmiy daraja to'g'risidagi diplomlar nusxasi"),
        ),
        migrations.AlterField(
            model_name='application',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='docs/passport/', verbose_name='Pasport yoki ID-shaxs guvohnomasi nusxasi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='rector_application',
            field=models.FileField(blank=True, null=True, upload_to='docs/rector/', verbose_name='Institut rektori nomiga ariza'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='docs/resume/', verbose_name="Rezyume-ma'lumotnoma"),
        ),
    ]
