# Generated by Django 6.0.7 on 2026-08-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_application_rejection_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='m_diploma',
            field=models.FileField(blank=True, null=True, upload_to='docs/m_diploma/', verbose_name="Magistr to'g'risidagi diplomlar nusxasi"),
        ),
        migrations.AddField(
            model_name='application',
            name='m_diploma_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='m_diploma_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20),
        ),
    ]
