server {
    listen 80;
    listen [::]:80;
    server_name ish.samdpi.uz;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        root /home/ali/ish;
    }

    location /media/ {
        root /home/ali/ish;
    }

    location / {
       include proxy_params;
       proxy_pass http://unix:/run/ish.sock;
    }
}
